/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      //font sizes
      fontSize: {
        llg: "20px",
        lx: "24px",
        lxx: "28px",
        xxl: "32px",
        xxxl: "48px",
        xxxxl: "64px",
      },
      colors: {
        primary: "#FDC157",
        yellowLight: "#FDF5D8",
        secondary: "#374151",
        paragraph: "#6b7280",
        darkGray: "#31363D",
        steal: "#777E90",
        darkSteal: "#79808E",
        gray700: "#141416",
        gray200: "#FCFCFD",
        bluish: "#172B4D",
        lightBlue: "#34495E",
        darkest: "#2C3E50",
        lightestPro: "#495057",
        lightest: "#95909E",
        grayPro: "#3D3D3D",
        grayMine: "#868491",
        graySuit: "#667085",
        grayWow: "#323548",
        grayBluish: "#344054",
        grayLight100: "#1A1A1A",
        grayHome: "#263238",
        graySuper: "#707281",
        primaryBg: "#FBFBFB",
        borderPrimary: "#E5E9F2",
        borderSecondary: "#E4E7EC",
        borderTertiary: "#D9D9D9",
        bgSecondary: "#141416",
        bgWhite: "#F7F7F8",
        hoverBg: "#E6E8EC",
        grayFilled: "#D1D5DB",
        grayOff: "#F6F7F8",
        darkBg: "#35383F99",
      },
      fontFamily: {
        sans: "Poppins, sans-serif",
        urban: "Urbanist, sans-serif",
        inter: "Inter, sans-serif",
        sf: "SF Pro Display, sans-serif",
      },
    },
  },
  plugins: [],
};
